const val space = " "
const val plus = "+"
const val minus = "-"
const val multiply = "*"
const val divide = "/"
const val increase = "++"
const val roundBracketOpen = "("
const val roundBracketClose = ")"
const val curlyBracketOpen = "{"
const val curlyBracketClose = "}"
const val assign = "="
const val equal = "=="
const val notEqual = "!="
const val lessThan = "<"
const val greaterThan = ">"
const val lessThanOrEqual = "<="
const val greaterThanOrEqual = ">="
const val semiColon = ";"
const val return_ = "return"
const val if_ = "if"
const val while_ = "while"
const val newLine = "\n"
val numbers = (0..9).map { it.toString() }
val alphabets = listOf('a'..'z', 'A'..'Z').flatten()
