enum class TokenType {
    PLUS,
    MINUS,
    MULTIPLY,
    DIVIDE,
    NUMBER,
    ROUND_BRACKET_OPEN,
    ROUND_BRACKET_CLOSE,
    EQUAL,
    NOT_EQUAL,
    LESS_THAN,
    GREATER_THAN,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN_OR_EQUAL,
    NULL//使わないはず
}